### ISSUE TITLE
Failed to run TPC-H Q1: MPPHandler: dispatch task meet error : CHECK failed: (index) < (current_size_)

### ISSUE THREAD

**Issue by riteme** [pingcap/tiflash#2737]
Commit hash: 7886e040149b33db8fdffee512578feb4f0e3fae

Error message:

```
2021.08.22 19:51:22.171924 [ 70 ] <Error> MPPHandler: dispatch task meet error : CHECK failed: (index) < (current_size_): 
```

TiFlash binary built with clang 12.0 and `libc++`, in Debug mode.

Cluster deployed by TiUP. Configuration:

```yaml
global:
  user: "root"
  ssh_port: 22
  deploy_dir: "/pingcap/run/tiup/cluster/tidb-deploy"
  data_dir: "/pingcap/run/tiup/cluster/tidb-data"
pd_servers:
  - host: 127.0.0.1
tidb_servers:
  - host: 127.0.0.1
tikv_servers:
  - host: 127.0.0.1
tiflash_servers:
  - host: 127.0.0.1
```

TPC-H data generated by TiUP with the following command:

```
tiup bench tpch --sf=1 prepare
```

Q1:

```sql
select
  l_returnflag,
  l_linestatus,
  sum(l_quantity) as sum_qty,
  sum(l_extendedprice) as sum_base_price,
  sum(l_extendedprice * (1 - l_discount)) as sum_disc_price,
  sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge,
  avg(l_quantity) as avg_qty,
  avg(l_extendedprice) as avg_price,
  avg(l_discount) as avg_disc,
  count(*) as count_order
from
  lineitem
where
  l_shipdate <= date_sub('1998-12-01', interval 108 day)
group by
  l_returnflag,
  l_linestatus
order by
  l_returnflag,
  l_linestatus;
```

and this query is executed in MySQL client.
