### ISSUE TITLE
Enhance default config behavior

### ISSUE THREAD

**Issue by breeswish** [pingcap/tiflash#4809]
## Enhancement

Currently many TiFlash config default values are evaluated in a wrong way. For example, given the following two config files, the evaluated final config are different!

**Config-A:** Final `enable_ps_v3 = false`

```toml
tcp_port = 9000
tmp_path = "/tmp/tiflash/data/tmp"
path = "/tmp/tiflash/data/db"

[storage]

[logger]
console = 1
level = "trace"
```

**Config-B:** Final `enable_ps_v3 = true`

```toml
tcp_port = 9000
tmp_path = "/tmp/tiflash/data/tmp"
path = "/tmp/tiflash/data/db"

# [storage]  <---- No storage section

[logger]
console = 1
level = "trace"
```

The root cause of **this specific issue** is that, `enable_ps_v3` is evaluated in the following way:

```cpp
if (config.has("storage"))
{
    storage_config.parseMisc(config.getString("storage"), log);
}

// In parseMisc:

if (table->contains("enable_ps_v3"))
{
    ...
}
else
{
    ...
    enable_ps_v3 = true;
}
```

Thus, if `[storage]` is not defined, the default value of `enable_ps_v3` will be evaluated different.

Throughout the whole code base, not only `enable_ps_v3`, but also other config items have similar problems.

We can improve the config architecture, to achieve these goals:

1. In the code base, there should be **only one** place defining the default value of config item.
2. The default value of each config is effective as long as this config item is not explicitly defined in the config file.
