### ISSUE TITLE
 TiFlash存算分离写节点高可用问题

### ISSUE THREAD

**Issue by lee1988well** [pingcap/tiflash#8774]
TiDB 版本：v7.5.0
我在测试存算分离架构的TiFlash遇到以下问题：

- 相关知识点：https://docs.pingcap.com/zh/tidb/stable/tiflash-disaggregated-and-s3
- 两个写节点
- 表副本数是两个
- 当我的一台写节点故障时，表不可访问：
`ERROR 1105 (HY000): other error for mpp stream: Code: 0, e.displayText() = DB::Exception: EstablishDisaggTask Failed14: failed to connect to all addresses, e.what() = DB::Exception,`
查看表的region的分布时，可以看到所有的region都有副本在存活的写节点上

遇到这个问题，应该如何快速修复，本来原来的架构的tiflash,是可以高可用的，那这个架构是不是存在单点故障了

**Comment by CalvinNeo** [comment]
Hi, this error is raised while we are reading, in which case, TiDB will communicate with TiFlash Compute nodes rather than TiFlash Write nodes, according to the given document.
So, above all, do you have configured any compute nodes? And if so, could you check if they are accessible from TiDB?

**Comment by lee1988well** [comment]
计算节点配置了3个，是正常的。如果将写节点重新启动，查询可以正常进行。过程中tikv也是正常的。
I have configured 3 compute nodes, and they are functioning properly. If I restart the write node, the queries can proceed normally. TiKV is also functioning normally during this process.

**Comment by CalvinNeo** [comment]
We suspect that the CN node failed to refresh its "available wn list" just in time. This could be some problem and we will have it looked into.
IMO, restarting CN nodes, or switching to using 1 replica may help, in these cases.
Meanwhile, could you tell me which of the two wn nodes have you restarted? Or you restarted all wn nodes?

**Comment by lee1988well** [comment]
我的操作步骤是：
第一步：tiup cluster stop xxx ---停止其中一个写节点
  此时所有的查询不可用
第二步：将表的两副本改为1副本
  此时可以看到表TIKV_REGION_STATUS还是存在不可用副本
  此时查询表，依然不可用
第三步：重启可用的写节点
  此时查询不可用
第四步：启动第一步关闭的写节点
  此时查询可用

高可用还是失败了，是不是需要我所有的表都设置成两副本才行吗

**Comment by CalvinNeo** [comment]
IMO, it could be a bug of TiFlash. Could you provide us some logs of TiFlash that we can look into?
/cc @JaySon-Huang

**Comment by CalvinNeo** [comment]
It is found that there are logs that complain about access denied from AWS. I think may be we have to check if some logs in topology.toml is correct.
Please check if the following config item is correctly set.
```
    config:
      storage.s3.bucket: 
      storage.s3.root: 
      storage.s3.endpoint: 
      storage.s3.access_key_id:
      storage.s3.secret_access_key:
    learner_config:
      dfs.prefix: 
      dfs.s3-endpoint: 
      dfs.s3-key-id: 
      dfs.s3-secret-key: 
      dfs.s3-bucket: 
      dfs.s3-region: 
```
