### ISSUE TITLE
TiFlash process get blocked when cpu_quota is less than 1 cpu

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#9488]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Deploy a tidb cluster using tiup with cpu_quota less than 100%

```
tiflash_servers:
- host: 127.0.0.1
  ...
  resource_control:
    cpu_quota: 80%
```

### 2. What did you expect to see? (Required)

tiflash starts normally or exit with explicit error message

### 3. What did you see instead (Required)

tiflash blocks forever

### 4. What is your TiFlash version? (Required)
master
